version: '3'
services:
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
        - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode=""
  backend:
    image: "ronaldgcr/api-dev-node-console:1.0.0"
    ports:
      - 80:3000    
    volumes:
      - ./app/:/app
    depends_on:
      - mysql    
    command: "yarn run-dev"
